### PR TITLE
Features: TODO Functionality & Colour Customization

### PR DESCRIPTION
**Pull request by adrian-miasik-2**
I couldn't personally resolve the merge conflict on #117 since I had no push authority on the forked repo, **so instead I've pulled @KingWazzack 's forked repo develop branch into this repos branch named: `develop-king-wazzack`**

Re-created using secondary account so @adrian-miasik can be formally/officially requested for review. (PR's opened by the same user can't be requested for review)

More context:
- Ended up merging in #117 into develop, instead of merging develop into #117. (Git Client GUI defaulted to our develop branch instead of @KingWazzack develop branch, which makes sense but has made accidentally merged in #117 into develop unintentionally)

---
Original Post by @KingWazzack:
---
Hi Adrian,

I have completed development on the functions we discussed earlier. 

Two new rows have been added to the sidebar, each with its corresponding pages.

Following Scripts have been Added: 
- TodoListManager.cs
- ListItem.cs
- CustomizationManager.cs
- TodoPage.cs
- CustomizationPage.cs

Following Scripts have been edited to implement new functionalities:
- HotkeyDetector.cs
- Page.cs
- PomodoroTimer.cs

I would appreciate it if you could find some time to review them. Please note that the implementation is not as polished as I would have liked, as I had limited time to work on it. I had to abandon the color picker concept and instead opted for input fields for entering hex values.

I'm looking forward to hearing your thoughts on it.

Kind regards,
Paul

- [x] Create a discussion page for your contribution / this PR (and provide a link below).
- [x] Adhereing to a very similar/same coding style in your code.
- [x] Tested this PR on as many target platforms as you could. If you’ve not tested this on certain platforms, please list out which one’s you haven’t tested below.

--- 

- Discussion URL: https://github.com/adrian-miasik/unity-pomodoro/discussions/116
- Platforms tested:
  - Mac
- Platforms that need further testing:
  - Windows
  - Android
  - Steam(?)

---

### CODE REVIEW

**Comment by adrian-miasik** [comment]
Alright, merge conflict has been resolved! 🎉 

I've re-added the develop branch (which includes the state indicators) into this branch.
I've also done some house-keeping with regards to script locations and script namespaces. So all @KingWazzack scripts sit in their own directory.

I've got to run for now, but next up for me: Code review + Integration decisions.

Not further action needed from @KingWazzack yet.

**Comment by adrian-miasik** [comment]
Played around a bit with the new changes :D 
Good stuff! 

I'd actually like to implement the color changes upstream!
However, in order to do that we'll need to address some of these points:

## Color Only PR
First off we'll need a PR with just the color changes.
- [ ] Create a new PR with just the color customization changes (Make sure that new PR has the latest develop branch merged in - forgo the TODO changes)

This way we can isolate and tackle the changes separately from the TODO list feature.

## Hex Code - Revert Option?
The hex codes works well, though one concern I have here is...once a user changes colors how do they revert them back? (Without knowing the original hex codes that is - and even if they did, the hex code is being applied to both light and dark themes at once)

It's possible that a user can change all the colors of the application and make everything invisible (so to speak). This wouldn't break functionality but it _**could**_ make the application practically unusable. If we had a button that reverted all colors back to the original factory default colors, this would alleviate the concern. Or perhaps a revert button for each ColorScheme property?
- [ ] Provide a way to reset/quickly fix unintended color changes

## Layout
- [ ] Fix title overlapping in customization page
- [ ] Fix customization page layout so elements don't overflow from timer bounds/viewport: We have to account for multiple aspect ratios/resolutions

## General Implementation
- [ ] Increase the height of the sidebar menu so we can see the page icons better/so they aren't as squished
- [ ] Re-order sidebar menu items so it follows this order:
	  - Pomodoro Timer
	  - Documentation
	  - Customization
	  - Settings
	  - About

## 'Save' Button
- [ ] Implement color support for the "Save" text to support light and dark themes.
- [ ] Add some form of player feedback to the "Save" button -> Convert from regular 'Unity Button' to 'ClickButtonText'?
- [ ] Fix button frame to not be circular but rounded rect -> https://github.com/kirevdokimov/Unity-UI-Rounded-Corners

I'm surprised you managed to get a lot done in such a short time frame.
I'd be happy to assist on any of these tasks if you'd like. 
Though if you are working on your forked repo, I'll need to be added as a collaborator to help with changes there. 

Once we tackle these concerns, then we can do a proper code review and work into getting this merged into the project.

In the meantime, I'll be looking into #118 and also modifying the credits bubble to include other users ;)

**Comment by adrian-miasik** [comment]
Heya @KingWazzack,

I've got some free time. I'm going to tackle some of the work to lighten the load. I'll take care of the "General Implementation" tasks and probably others later (will communicate them as I go). I'll be working on the 'develop-king-wazzack' branch. I advise using this branch as your starting point for the other tasks. Oh, and if you have no time or bandwidth for crossing this to the finish line, I'll be happy to take it off your shoulders too. Just let me know, cheers.

**Comment by adrian-miasik** [comment]
I've finished with the **General Implementation** and also tweaked the **Layout** for the customization page to support more resolutions/aspect ratios. I'm done modifying this branch and the main scene for the time being. You're welcome to make changes to this branch and or the main scene as well.

**Comment by adrian-miasik** [comment]
Hey @Kr0sFyr3, 

I'm marking this PR as abandoned for the time being. If you'd still like to get this merged in, please reach out either here or email me back. 

Good luck with the rest of your studies!

**Comment by Kr0sFyr3** [comment]
Unfortunately i have been swamped with work as off lately. However if i do have some sparetime to work on this i'll hit you up. Since i don't really enjoy having to abandon or leave work unfinished, i aim to finish this contribution at one point but unfortunately i have a lot of work that has a higher priority in my personal backlog. I'll stay in touch!

-Paul

**Comment by adrian-miasik** [comment]
Totally understandable! When you're ready to tackle this, I'll be here :)

**Pull request closed without merging**
